# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 467bf2ee5abbd2bc8aba8355e0becdfdfdf0c56720c4bfb14f40244f9743bc597ac994f46e1456a9041455e5e3732ae3a21ca608ea0993fc8332eec6828c3286

test:
  secret_key_base: add2befc591df936e1b49ca06ecf755599b7fa5e8097886d6714170b87ed61bed0d5833a4beb0cc417f8d2169edea802669e52ea876949133c94d684427f5d8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
